 #This is a basic workflow to help you get started with Actions

name: Deployment of React on Surge 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request: 
          branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install NodeJS
    - uses: actions/setup-node@v2-beta
      with:
        version: 12
    
    # Install Yarn
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    
    # Build App
    - name: Build App
      run: yarn build
    
    # Install Surge
    - name: Install Surge
      run: npm install -g surge
    
    # Deploy to Surge
    - name: Deploy app
      run: surge ./build react-class2assignment-saad.surge.sh/ --token ${{secrets.surge_token}}
